name: pytorch-autoencoder
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cpython=3.10.15=py310hd8ed1ab_1
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.6=3
  - debugpy=1.8.7=py310h9e98ed7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - filelock=3.13.1=py310haa95532_0
  - freetype=2.12.1=ha860e81_0
  - fsspec=2024.6.1=py310haa95532_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - idna=3.7=py310haa95532_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.28.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py310haa95532_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=8_h719fc58_netlib
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=8_h719fc58_netlib
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - llvmlite=0.43.0=py310hf2fb9eb_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.3=py310h2bbff1b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.10=py310h827c3e9_0
  - mkl_random=1.2.7=py310hc64d2fc_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=py310haa95532_0
  - numba=0.60.0=py310h7793332_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.4.0=h2466b09_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py310h827c3e9_0
  - pip=24.2=py310haa95532_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py310ha8f682b_2
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhff2d567_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.15=h4607a30_1
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.4.1=py3.10_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pywin32=307=py310h9e98ed7_3
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=26.2.0=py310h656833d_3
  - requests=2.32.3=py310haa95532_0
  - scikit-learn=1.5.2=py310hf2a6c47_1
  - scipy=1.14.1=py310hbd0dde3_1
  - setuptools=75.1.0=py310haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.13.2=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.1=py310ha8f682b_1
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py310haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - umap-learn=0.5.7=py310h5588dad_0
  - urllib3=2.2.3=py310haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=hcc2c482_22
  - vs2015_runtime=14.40.33810=h3bf8584_22
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=ha9f60a1_6
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - altair==5.5.0
      - attrs==24.2.0
      - audioread==3.0.1
      - bleach==6.2.0
      - blinker==1.9.0
      - bokeh==3.6.1
      - cachetools==5.5.0
      - cffi==1.17.1
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorcet==3.1.0
      - contourpy==1.3.0
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2024.11.2
      - datashader==0.16.3
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - flask==3.0.3
      - fonttools==4.54.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - holoviews==1.20.0
      - imageio==2.36.1
      - imbalanced-learn==0.13.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - linkify-it-py==2.0.3
      - locket==1.0.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - msgpack==1.1.0
      - multipledispatch==1.0.0
      - narwhals==1.15.2
      - nbformat==5.10.4
      - onnx==1.17.0
      - opencv-python==4.10.0.84
      - pandas==2.2.3
      - panel==1.5.4
      - param==2.1.1
      - partd==1.4.2
      - plotly==5.24.1
      - pooch==1.8.2
      - protobuf==5.28.2
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pycparser==2.22
      - pyct==0.5.0
      - pydeck==0.9.1
      - pyparsing==3.2.0
      - pytz==2024.2
      - pyviz-comms==3.0.3
      - referencing==0.35.1
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.22.0
      - scikit-image==0.24.0
      - seaborn==0.13.2
      - sklearn-compat==0.1.3
      - smmap==5.0.1
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - streamlit==1.40.2
      - streamlit-plotly-events==0.0.6
      - tenacity==9.0.0
      - tifffile==2024.9.20
      - toml==0.10.2
      - toolz==1.0.0
      - torchaudio==2.4.1
      - torchsummary==1.5.1
      - torchvision==0.19.1
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - ultralytics==8.3.61
      - ultralytics-thop==2.0.13
      - watchdog==6.0.0
      - webencodings==0.5.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - xarray==2024.11.0
      - xyzservices==2024.9.0
